### ISSUE TITLE
Postgres Driver is not working

### ISSUE THREAD

**Issue by yphanikumar1995** [Erudika/para-dao-sql#14]
I downloaded the para-dao-sql jar file  to inside  lib folder and restarted the para container but iam getting below error

```
2022-08-18 07:06:25 [ERROR] Error loading SQL driver "org.postgresql.Driver", class not found.
2022-08-18 07:06:55 [ERROR] Error loading SQL driver "org.postgresql.Driver", class not found.
2022-08-18 07:07:25 [ERROR] Error loading SQL driver "org.postgresql.Driver", class not found.
2022-08-18 07:07:55 [ERROR] Error loading SQL driver "org.postgresql.Driver", class not found.
```

I used below setting in para
```
para.dao = "SqlDAO"
para.sql.driver = "org.postgresql.Driver"
para.sql.url = "postgresql://postgres:5432"
para.sql.user = "postgres"
para.sql.password = "password"
```

any other configuration required  ?

**Comment by albogdano** [comment]
Do you have the PostgreSQL connector driver JAR file inside `./lib` directory? You may have to start Para with this command:
```
java -jar -Dloader.path=./lib -Dconfig.file=./para-application.conf para.jar
```

**Comment by yphanikumar1995** [comment]
Hi @albogdano , thanks 
it is worked after i added the postgres jdbc jar into lib folder
https://jdbc.postgresql.org/download.html
i am using below Dockerfile , it may help for someone
```
FROM erudikaltd/para:v1.46.1 AS base
FROM erudikaltd/para-dao-sql:1.45.4 AS dao
FROM base AS final
COPY --from=dao /para/lib/*.jar /para/lib
ADD https://jdbc.postgresql.org/download/postgresql-42.4.2.jar /para/lib
RUN chmod -R 755 /para/lib
```

**Comment by mljohns89** [comment]
For me it was:
```
env:
- name: LOADER_PATH
   value: "lib"
```

**Comment by albogdano** [comment]
An ENV variable `LOADER_PATH` probably won't work. It has to be a system property named `loader.path`.

**Comment by mljohns89** [comment]
I'm building a helm chart and on v1.47.2.  I tried everything and setting
the LOADER_PATH env variable was the ONLY thing that worked.

**Comment by albogdano** [comment]
@mljohns89 Thank you for clarifying that! I was not sure because that property is part of Spring, not Para.
