### ISSUE TITLE
MySQL and PostgreSQL don't have MERGE statement.

### ISSUE THREAD

**Issue by mzch** [Erudika/para-dao-sql#2]
Hi,

Para use MERGE statement in its queries but MySQL, MariaDB and PostgreSQL don't have MERGE.
Instead their developers recommend to use INSERT. I'd like you to fix this issue.

**Comment by albogdano** [comment]
Hi Koichi, The `MERGE` statement is not actually used when the SQL plugin detects a MySQL or PostreSQL driver. So if you are using these databases you shouldn't have problems because the code will switch to `INSERT` automatically.

**Comment by mzch** [comment]
Sorry, I jumped the gun... I tried again, scoold booted normally, but I've failed to sign up. Using both MySQL and PostgreSQL, when clicking a link in a welcome mail, Confirmation screen is never shown and immediately shown Signin screen, of course, sign-in always fails using email/password which registered at sign up... When using MongoDB, scoold works correctly.

Well, BTW, Please add support of MariaDB Driver, whose forName is "org.mariadb.jdbc.Driver".

Thanks.

**Comment by mzch** [comment]
Since I didn't delete data/ directory at every trial, I failed to sign up. Sorry.

**Comment by albogdano** [comment]
I've added support for MariaDB. Thanks for the suggestion!
